<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Mekarjaya Coffee</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    {{-- Lucide Icons --}}
    <script src="https://unpkg.com/lucide@latest"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <style>
        html {
            scroll-behavior: smooth;
        }

        .hero-container {
            position: relative;
            overflow: hidden;
            height: 100vh;
        }

        .hero-track {
            display: flex;
            height: 100%;
            transition: transform 1.2s cubic-bezier(0.4, 0, 0.2, 1);
        }

        .hero-slide-item {
            flex: 0 0 100%;
            height: 100%;
            background-size: cover;
            background-position: center;
        }

        .hero-dot {
            width: 12px;
            height: 12px;
            border-radius: 99px;
            background: rgba(255, 255, 255, 0.3);
            cursor: pointer;
            transition: all 0.4s ease;
        }

        .hero-dot.active {
            background: #b91c1c;
            /* red-700 */
            width: 32px;
            box-shadow: 0 0 10px rgba(185, 28, 28, 0.6);
        }
    </style>
</head>

<body class="bg-[#f4f4f4] text-gray-900">

    {{-- Navbar --}}
    <nav class="fixed top-0 left-0 w-full z-50 bg-white/90 backdrop-blur shadow-sm">
        <div class="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
            <div class="flex items-center gap-3">
                <img src="{{ asset('images/logo.png') }}" alt="Logo" class="w-14 h-14 object-contain">
                <h1 class="text-3xl font-black text-[#DA291C] uppercase tracking-tighter font-poppins">Mekarjaya</h1>
            </div>

            <div class="hidden md:flex items-center gap-8 text-lg">
                <a href="#hero" class="hover:text-red-700">Home</a>
                <a href="#about" class="hover:text-red-700">About</a>
                <a href="#menu" class="hover:text-red-700">Menu</a>
                <a href="#ulasan" class="hover:text-red-700">Ulasan</a>
            </div>
        </div>
    </nav>

    {{-- Hero --}}
    <section id="hero" class="hero-container">
        {{-- Sliding Background Track --}}
        <div id="hero-track" class="hero-track">
            <div class="hero-slide-item" style="background-image: url('{{ asset('images/hero-coffee.jpg') }}');"></div>
            <div class="hero-slide-item" style="background-image: url('{{ asset('images/gallery_1.png') }}');"></div>
            <div class="hero-slide-item" style="background-image: url('{{ asset('images/gallery_2.png') }}');"></div>
            <div class="hero-slide-item" style="background-image: url('{{ asset('images/gallery_3.png') }}');"></div>
        </div>

        {{-- Fixed Overlays and Content --}}
        <div class="absolute inset-0 bg-black/55"></div>

        <div class="absolute inset-0 flex items-center justify-center z-10 text-center px-6">
            <div class="max-w-4xl">
                <h1 class="text-white text-5xl md:text-7xl font-light leading-tight mb-8 font-poppins">
                    Mekarjaya, <br> Just for you!
                </h1>
                <p class="text-white/90 text-xl md:text-3xl mb-10 font-serif">
                    Mekarjaya Coffee menyajikan kopi berkualitas <br>
                    dengan suasana nyaman dan minimalis.
                </p>
                <a href="#menu" class="bg-white text-gray-900 px-10 py-4 rounded-2xl text-2xl shadow hover:bg-gray-200">
                    Order Now
                </a>
            </div>
        </div>

        {{-- Pagination Dots --}}
        <div class="absolute bottom-10 left-1/2 -translate-x-1/2 z-20 flex gap-3" id="hero-dots">
            {{-- Generated by JS --}}
        </div>
    </section>

    {{-- About --}}
    <section id="about" class="py-24 bg-[#f4f4f4]">
        <div class="max-w-7xl mx-auto px-6 grid md:grid-cols-2 gap-12 items-center">
            <div class="reveal">
                <img src="{{ asset('images/about-coffee.png') }}" alt="About Coffee" class="w-full max-w-lg mx-auto">
            </div>

            <div class="reveal delay-200">
                <h2 class="text-6xl font-serif mb-6">About Us</h2>
                <p class="text-red-600 text-2xl mb-4">
                    Just For You <span class="text-gray-800 text-xl">Every cup tells a story</span>
                </p>
                <p class="text-xl leading-relaxed mb-6">
                    Mekarjaya Coffee adalah tempat di mana aroma kopi segar bertemu dengan suasana hangat.
                    Kami menghadirkan kopi berkualitas dari biji pilihan, diseduh dengan penuh perhatian untuk
                    menciptakan rasa terbaik di setiap cangkir.
                </p>
                <p class="text-xl leading-relaxed mb-8">
                    Tidak hanya kopi, kami juga menyediakan berbagai minuman dan camilan yang cocok untuk menemani
                    waktu santai, bekerja, maupun berkumpul bersama orang terdekat.
                </p>

                <a href="#menu" class="bg-red-400 text-white px-6 py-3 rounded-full hover:bg-red-500">
                    View our menu
                </a>
            </div>
        </div>
    </section>

    {{-- Best Seller --}}
    <section id="bestseller" class="pt-24 pb-8 bg-[#f4f4f4]">
        <div class="max-w-7xl mx-auto px-6">
            <div class="reveal">
                <h2 class="text-5xl font-bold text-center text-red-700 mb-12">Best Seller</h2>

                <div class="grid md:grid-cols-3 gap-8">
                    @foreach($bestSellers as $item)
                        <div
                            class="bg-white rounded-3xl shadow-lg p-8 text-center hover:shadow-2xl transition relative overflow-hidden group">
                            @if($item->is_best_seller)
                                <div class="absolute top-0 right-0">
                                    <div
                                        class="bg-yellow-400 text-white px-10 py-1 rotate-45 translate-x-8 translate-y-3 shadow-md font-bold text-xs uppercase tracking-widest border border-yellow-300">
                                        Best
                                    </div>
                                </div>
                            @endif
                            <div class="mb-4">
                                @if($item->image)
                                    <img src="{{ asset('storage/' . $item->image) }}" alt="{{ $item->name }}"
                                        class="w-44 h-44 object-contain mx-auto group-hover:scale-110 transition duration-500">
                                @else
                                    <img src="{{ asset('images/default-menu.png') }}" alt="{{ $item->name }}"
                                        class="w-44 h-44 object-contain mx-auto group-hover:scale-110 transition duration-500">
                                @endif
                            </div>
                            <h3 class="text-2xl font-bold mb-2">{{ $item->name }}</h3>
                            <p class="text-gray-600 mb-4">{{ $item->description }}</p>
                            <div class="flex items-center justify-center gap-3">
                                @if($item->discount_amount > 0)
                                    <p class="text-sm line-through text-red-300">Rp
                                        {{ number_format($item->price, 0, ',', '.') }}</p>
                                @endif
                                <p class="text-2xl font-black text-red-700">Rp
                                    {{ number_format($item->final_price, 0, ',', '.') }}</p>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </section>

    {{-- Our Menu --}}
    <section id="menu" class="pt-12 pb-24 bg-[#f4f4f4]">
        <div class="max-w-7xl mx-auto px-6">
            <div class="text-center mb-14 pt-10 border-t border-gray-200 reveal">
                <h2 class="text-6xl font-bold text-red-700 mb-6">Our Menu</h2>
                <p class="text-2xl max-w-4xl mx-auto font-semibold">
                    Enjoy a variety of delightful drinks and light meals crafted to complement your coffee experience.
                </p>
            </div>

            {{-- kategori --}}
            <div class="flex flex-wrap justify-center gap-4 mb-14">
                <button onclick="filterMenu('all')"
                    class="filter-btn bg-red-700 text-white px-8 py-3 rounded-xl text-xl">
                    View All
                </button>

                @foreach($categories as $category)
                    <button onclick="filterMenu('{{ $category->id }}')"
                        class="filter-btn bg-red-700 text-white px-8 py-3 rounded-xl text-xl">
                        {{ $category->name }}
                    </button>
                @endforeach
            </div>

            {{-- list menu per kategori --}}
            @foreach($categories as $category)
                @if($category->menus->count())
                    <div class="menu-group mb-16" data-category="{{ $category->id }}">
                        <h3 class="inline-block bg-red-700 text-white px-8 py-3 rounded-2xl text-2xl font-semibold mb-10">
                            {{ $category->name }}
                        </h3>

                        <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
                            @foreach($category->menus as $menu)
                                <div
                                    class="bg-white rounded-3xl shadow-md p-6 flex items-center justify-between hover:shadow-xl transition">
                                    <div class="pr-4">
                                        <h4 class="text-2xl font-semibold mb-2">{{ $menu->name }}</h4>
                                        <p class="text-gray-600 mb-4">{{ $menu->description }}</p>
                                        <div class="flex items-center gap-2">
                                            @if($menu->discount_amount > 0)
                                                <p class="text-sm line-through text-gray-400">Rp
                                                    {{ number_format($menu->price, 0, ',', '.') }}</p>
                                            @endif
                                            <p class="text-xl font-bold text-gray-800">Rp
                                                {{ number_format($menu->final_price, 0, ',', '.') }}</p>
                                        </div>
                                    </div>

                                    <div class="relative">
                                        @if($menu->is_best_seller)
                                            <div class="absolute -top-7 -right-4 z-10 rotate-12 scale-110">
                                                <div
                                                    class="bg-yellow-400 text-white p-2 rounded-full shadow-lg border-2 border-white flex items-center justify-center">
                                                    <i data-lucide="star" class="w-6 h-6 fill-current"></i>
                                                </div>
                                            </div>
                                        @endif

                                        @if($menu->image)
                                            <img src="{{ asset('storage/' . $menu->image) }}" alt="{{ $menu->name }}"
                                                class="w-32 h-32 object-contain">
                                        @else
                                            <img src="{{ asset('images/default-menu.png') }}" alt="{{ $menu->name }}"
                                                class="w-32 h-32 object-contain">
                                        @endif
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                @endif
            @endforeach


        </div>
    </section>

    {{-- Gallery / Suasana --}}
    <section id="gallery" class="py-24 bg-white">
        <div class="max-w-7xl mx-auto px-6 text-center">
            <h2 class="text-5xl font-bold text-red-700 mb-16 reveal font-poppins">Suasana Mekarjaya</h2>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
                <div class="overflow-hidden rounded-[40px] shadow-lg reveal delay-100">
                    <img src="{{ asset('images/gallery_1.png') }}" alt="Interior 1"
                        class="w-full h-[500px] object-cover hover:scale-110 transition duration-700">
                </div>
                <div class="overflow-hidden rounded-[40px] shadow-lg reveal delay-300">
                    <img src="{{ asset('images/gallery_2.png') }}" alt="Coffee 1"
                        class="w-full h-[500px] object-cover hover:scale-110 transition duration-700">
                </div>
                <div class="overflow-hidden rounded-[40px] shadow-lg reveal delay-500">
                    <img src="{{ asset('images/gallery_3.png') }}" alt="Exterior 1"
                        class="w-full h-[500px] object-cover hover:scale-110 transition duration-700">
                </div>
            </div>
        </div>
    </section>

    {{-- Maps --}}
    <section id="maps" class="pt-24 pb-12 bg-[#f4f4f4]">
        <div class="max-w-6xl mx-auto px-6">
            <h2 class="text-5xl font-bold text-red-700 text-center mb-16">Kunjungi Kami</h2>
            <div class="overflow-hidden rounded-[30px] shadow-2xl border-4 border-white">
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d247.70507656175383!2d106.7812511789058!3d-6.6119379886677345!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69c5001b1da1d3%3A0x933528604d9819f4!2sMekarjaya%20Coffee%2C%20Bogor!5e0!3m2!1sid!2sid!4v1775496696914!5m2!1sid!2sid"
                    width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                    referrerpolicy="no-referrer-when-downgrade">
                </iframe>
            </div>
        </div>
    </section>

    {{-- Ulasan --}}
    <section id="ulasan" class="py-24 bg-[#f4f4f4]">
        <div class="max-w-6xl mx-auto px-6">
            <h2 class="text-5xl font-bold text-red-700 text-center mb-16">Beri Kami Ulasan</h2>

            @if(session('success'))
                <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-6 text-center"
                    role="alert">
                    <span class="block sm:inline">{{ session('success') }}</span>
                </div>
            @endif

            <div class="grid md:grid-cols-2 gap-12 items-center">
                <form method="POST" action="{{ route('reviews.store') }}" class="space-y-5">
                    @csrf
                    <div class="grid md:grid-cols-2 gap-4">
                        <input type="email" name="email" placeholder="Email (Opsional)"
                            class="w-full rounded-xl border-0 bg-gray-200 px-4 py-4 focus:ring-2 focus:ring-red-500">
                        <input type="text" name="name" placeholder="Nama Anda" required
                            class="w-full rounded-xl border-0 bg-gray-200 px-4 py-4 focus:ring-2 focus:ring-red-500">
                    </div>

                    <textarea name="message" rows="8" placeholder="Tulis ulasan Anda di sini..." required
                        class="w-full rounded-xl border-0 bg-gray-200 px-4 py-4 focus:ring-2 focus:ring-red-500"></textarea>

                    <button type="submit" class="bg-red-700 text-white px-10 py-3 rounded-xl hover:bg-red-800">
                        Kirim Ulasan
                    </button>
                </form>

                <div class="text-center">
                    <img src="{{ asset('images/logo.png') }}" alt="Logo Mekarjaya" class="w-56 mx-auto drop-shadow-2xl">
                </div>
            </div>
        </div>
    </section>


    {{-- Footer & Jam Operasional --}}
    <footer class="bg-gray-900 text-white pt-24 pb-12">
        <div class="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-3 gap-16 mb-16">
            {{-- Brand info --}}
            <div class="reveal">
                <div class="flex items-center gap-3 mb-6">
                    <img src="{{ asset('images/logo.png') }}" alt="Logo" class="w-14 h-14">
                    <h2 class="text-3xl font-bold uppercase tracking-widest text-[#DA291C] font-poppins">Mekarjaya</h2>
                </div>
                <p class="text-gray-400 text-lg leading-relaxed">
                    Lebih dari sekadar kopi. Kami menyajikan kenyamanan dan cerita di setiap cangkir yang Anda nikmati.
                </p>
                <div class="flex gap-4 mt-8">
                    {{-- Instagram --}}
                    <a href="https://www.instagram.com/mekarjayacoffee.id?igsh=YXB2djJ6cmF1dnp" target="_blank"
                        class="w-10 h-10 rounded-full bg-gray-800 text-white flex items-center justify-center hover:bg-[#E1306C] transition shadow-lg">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 fill-current" viewBox="0 0 24 24"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zM12 0C8.741 0 8.333.014 7.053.072 2.695.272.273 2.69.073 7.052.014 8.333 0 8.741 0 12c0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98C8.333 23.986 8.741 24 12 24c3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98C15.668.014 15.259 0 12 0zm0 5.838a6.162 6.162 0 100 12.324 6.162 6.162 0 000-12.324zM12 16a4 4 0 110-8 4 4 0 010 8zm6.406-11.845a1.44 1.44 0 100 2.881 1.44 1.44 0 000-2.881z"/></svg>
                    </a>
                    
                    {{-- TikTok --}}
                    <a href="https://www.tiktok.com/@mekarjayacoffee?_r=1&_t=ZS-96BBFLvMgem" target="_blank"
                        class="w-10 h-10 rounded-full bg-gray-800 text-white flex items-center justify-center hover:bg-[#00f2fe] transition shadow-lg group">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 fill-current group-hover:text-black transition" viewBox="0 0 24 24"><path d="M12.525.02c1.31-.02 2.61-.01 3.91-.02.08 1.53.63 3.09 1.75 4.17 1.12 1.11 2.7 1.62 4.24 1.79v4.03c-1.44-.05-2.89-.35-4.2-.97-.57-.26-1.1-.59-1.62-.93-.01 2.92.01 5.84-.02 8.75-.08 2.12-1.02 4.13-2.5 5.57-1.46 1.45-3.44 2.32-5.41 2.56-2.31.25-4.72-.08-6.72-1.28-1.97-1.16-3.35-2.92-3.92-5.02-.6-2.13-.38-4.43.58-6.38 1.01-2.03 2.75-3.56 4.9-4.2 2.14-.65 4.54-.53 6.55.33.05.51.05 1.02.05 1.53-.02 1.08-.03 2.17-.05 3.25-1.12-.51-2.42-.64-3.62-.35-1.18.27-2.18 1.05-2.73 2.08-.54 1.04-.66 2.27-.33 3.39.31 1.1.99 2.05 1.94 2.62 1.02.59 2.26.74 3.39.46 1.25-.3 2.3-1.18 2.82-2.33.28-.62.4-1.3.4-1.99.01-4.8.01-9.61 0-14.41z"/></svg>
                    </a>

                    {{-- Grab --}}
                    <a href="https://r.grab.com/g/6-20260508_102728_b25a5d1382424678b4b7878cf29a8392_MEXMPS-6-C7VATLAZUFWWTN" target="_blank"
                        class="w-10 h-10 rounded-full bg-gray-800 text-white flex items-center justify-center hover:bg-[#00B14F] transition shadow-lg">
                        <span class="font-black text-[10px] tracking-tight">Grab</span>
                    </a>
                </div>
            </div>

            {{-- Jam Operasional --}}
            <div class="reveal delay-200">
                <h3 class="text-2xl font-bold mb-8 border-b border-gray-700 pb-2 inline-block">Jam Operasional</h3>
                <ul class="space-y-4 text-lg">
                    <li class="flex justify-between">
                        <span class="text-gray-400">Selasa - Jumat</span>
                        <span class="font-semibold">09.00 - 21.00</span>
                    </li>
                    <li class="flex justify-between">
                        <span class="text-gray-400">Sabtu - Minggu</span>
                        <span class="font-semibold">09.00 - 22.00</span>
                    </li>
                    <li class="flex justify-between">
                        <span class="text-gray-400">Senin Libur</span>
                    </li>
                </ul>
                <div class="mt-8 pt-6 border-t border-gray-800">
                    <p class="text-sm italic text-red-400 font-medium">Buka setiap hari kecuali hari senin dan hari besar tertentu.</p>
                </div>
            </div>

            {{-- Hubungi Kami --}}
            <div class="reveal delay-400">
                <h3 class="text-2xl font-bold mb-8 border-b border-gray-700 pb-2 inline-block">Lokasi & Kontak</h3>
                <ul class="space-y-4 text-lg text-gray-400">
                    <li class="flex gap-3">
                        <i data-lucide="map-pin" class="w-6 h-6 text-red-500 shrink-0"></i>
                        <span>Komplek Mekarbaru Blok E4, Mekarjaya, Kec. Ciomas, Kabupaten Bogor, Jawa Barat</span>
                    </li>
                    <li class="flex gap-3">
                        <i data-lucide="phone" class="w-6 h-6 text-red-500 shrink-0"></i>
                        <span>085163686991</span>
                    </li>
                    <li class="flex gap-3">
                        <i data-lucide="mail" class="w-6 h-6 text-red-500 shrink-0"></i>
                        <span>coffeemekarjaya@gmail.com</span>
                    </li>
                </ul>
            </div>
        </div>

        <div
            class="max-w-7xl mx-auto px-6 pt-8 border-t border-gray-800 flex flex-col md:flex-row justify-between items-center gap-4 text-gray-500 text-sm">
            <p>&copy; 2026 Mekarjaya Coffee. All rights reserved.</p>
            <div class="flex gap-6">
                <a href="#" class="hover:text-white transition">Privacy Policy</a>
                <a href="#" class="hover:text-white transition">Terms of Service</a>
            </div>
        </div>
    </footer>

    {{-- WhatsApp Floating Button --}}
    <a href="https://wa.me/6281234567890" target="_blank"
        class="fixed bottom-10 right-10 z-50 bg-[#25D366] text-white p-4 rounded-full shadow-2xl hover:scale-110 active:scale-95 transition-all group flex items-center gap-2 overflow-hidden max-w-[60px] hover:max-w-[200px] duration-500">
        <i data-lucide="message-circle" class="w-8 h-8"></i>
        <span
            class="font-bold opacity-0 group-hover:opacity-100 whitespace-nowrap pr-4 transition-all duration-500">Chat
            Mekarjaya</span>
    </a>

    {{-- Script & Styles --}}
    <style>
        .reveal {
            opacity: 0;
            transform: translateY(30px);
            transition: all 0.8s ease-out;
        }

        .reveal.active {
            opacity: 1;
            transform: translateY(0);
        }

        .delay-100 {
            transition-delay: 0.1s;
        }

        .delay-200 {
            transition-delay: 0.2s;
        }

        .delay-300 {
            transition-delay: 0.3s;
        }

        .delay-400 {
            transition-delay: 0.4s;
        }

        .delay-500 {
            transition-delay: 0.5s;
        }
    </style>

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            lucide.createIcons();

            // Scroll Reveal Animation
            const observer = new IntersectionObserver((entries) => {
                entries.forEach((entry) => {
                    if (entry.isIntersecting) {
                        entry.target.classList.add("active");
                    }
                });
            }, {
                threshold: 0.15
            });

            document.querySelectorAll(".reveal").forEach((el) => {
                observer.observe(el);
            });
        });

        // Menu Filter
        function filterMenu(categoryId) {
            const groups = document.querySelectorAll('.menu-group');
            groups.forEach(group => {
                if (categoryId === 'all') {
                    group.style.display = 'block';
                } else {
                    group.style.display = group.dataset.category === categoryId ? 'block' : 'none';
                }
            });
        }
        // Hero Sliding Carousel
        document.addEventListener("DOMContentLoaded", function () {
            const track = document.getElementById('hero-track');
            const dotsContainer = document.getElementById('hero-dots');
            const slides = document.querySelectorAll('.hero-slide-item');
            let currentIndex = 0;
            let slideInterval;

            // Generate Dots
            slides.forEach((_, index) => {
                const dot = document.createElement('div');
                dot.classList.add('hero-dot');
                if (index === 0) dot.classList.add('active');
                dot.addEventListener('click', () => goToSlide(index));
                dotsContainer.appendChild(dot);
            });

            const dots = document.querySelectorAll('.hero-dot');

            function goToSlide(index) {
                currentIndex = index;
                track.style.transform = `translateX(-${currentIndex * 100}%)`;

                // Update Dots
                dots.forEach(d => d.classList.remove('active'));
                dots[currentIndex].classList.add('active');

                // Reset Interval
                clearInterval(slideInterval);
                startInterval();
            }

            function nextSlide() {
                let nextIndex = (currentIndex + 1) % slides.length;
                goToSlide(nextIndex);
            }

            function startInterval() {
                slideInterval = setInterval(nextSlide, 10000);
            }

            startInterval();
        });
    </script>
</body>

</html>